pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["administracion.htm","Administracion","Administracion Top Previous Next Enter topic text here. ",""],
["alumnos.htm","Entidades","Entidades Top Previous Next Enter topic text here. ",""],
["asignatura.htm","Asignatura","Asignatura Top Previous Next Corresponde a las diferentes asignaturas que se dictan en el establecimiento educativo en los correspondientes nivele...",""],
["aula.htm","Aula","Aula Top Previous Next Nueva Aula Al presionar el sistema habilita los campos a ingresar por el usuario. Dichos campos son: Nombre: es el nombre q...",""],
["bienvenidos_a_sige.htm","Bienvenidos a SIGE","Bienvenidos a SIGE Top Next SIGE es un sistema integral para la gestión escolar y académica que permite automatizar gran parte de las tareas rutin...",""],
["cobro.htm","Cobro","Cobro Top Previous Enter topic text here. ",""],
["configuracion.htm","Configuracion","Configuracion Top Previous Next Enter topic text here. ",""],
["curso.htm","Curso","Curso Top Previous Next ........................................... Nuevo Curso Al presionar el boton el sistema habilita los campos a ingresar po...",""],
["docente.htm","Docente","Docente Top Previous Next Personal docente hace referencia a toda aquella persona que trabaje en el establecimiento educativo, la cual esté involu...",""],
["generacion_de_reporte.htm","Generacion de Reporte","Generacion de Reporte Top Previous Next Enter topic text here. ",""],
["inscripcion_alumno.htm","Alumno","Alumno Top Previous Next Alumno hace referencia a los que concurren al establecimiento para desarrollar sus actividades educativas. Nuevo Alumno 1...",""],
["introduccion.htm","Introduccion","Introduccion Top Previous Next El propósito de este manual es describir como se utilizara el Sistema de Información de Gestión Educativa. A contin...",""],
["parametros.htm","Parametros","Parametros Top Previous Next Enter topic text here. ",""],
["personal_maestranaz.htm","Personal Maestranza","Personal Maestranza Top Previous Next Personal de maestranza hace referencia a toda aquella persona que trabaje en el establecimiento educativo, l...",""],
["reportes.htm","Reportes","Reportes Top Previous Next Enter topic text here. ",""],
["tutor.htm","Tutor","Tutor Top Previous Next Es quien .......................... Nuevo Tutor Al presionar el boton el sistema habilita los campos a ingresar por el usu...",""],
["usuarios.htm","Usuarios","Usuarios Top Previous Next Enter topic text here. ",""]];
